/**
 * GENERATED by `npm run gen:api` (scripts/api-contract-smoke.mjs --emit-allowlist)
 * from https://mesonet2.climate.umt.edu/api/openapi.json. Do not edit by hand;
 * add hidden routes to HIDDEN in that script instead.
 *
 * Per-endpoint GET query-parameter allowlist enforced by `core/api/http.ts`.
 * Keys are OpenAPI path templates (leading + trailing slash).
 */

export const SPEC_PARAM_ALLOWLIST: Readonly<Record<string, readonly string[]>> = {
  '/config/{station}/': [],
  '/derived/': ['dates', 'elements', 'end_time', 'grouped', 'keep', 'level', 'na_info', 'nomid', 'rm_na', 'simple_datetime', 'split_ppt', 'start_time', 'stations', 'time', 'type', 'tz', 'units', 'wide'],
  '/derived/change/': ['difference', 'stations', 'type'],
  '/derived/daily/': ['alpha', 'crop', 'dates', 'elements', 'end_time', 'grouped', 'high', 'keep', 'level', 'low', 'na_info', 'nomid', 'rm_na', 'simple_datetime', 'split_ppt', 'start_time', 'stations', 'time', 'type', 'tz', 'units', 'wide'],
  '/derived/hourly/': ['alpha', 'dates', 'elements', 'end_time', 'grouped', 'keep', 'level', 'na_info', 'nomid', 'rm_na', 'simple_datetime', 'split_ppt', 'start_time', 'stations', 'time', 'type', 'tz', 'units', 'wide'],
  '/derived/ppt/': ['since', 'split_ppt', 'stations', 'type', 'wide'],
  '/elements/': ['all', 'grouped', 'nomid', 'public', 'type'],
  '/elements/{station}/': ['end_time', 'grouped', 'nomid', 'public', 'start_time', 'type', 'tz'],
  '/ghcn/': ['end_time', 'level', 'period', 'start_time', 'type', 'tz'],
  '/latest/': ['active', 'elements', 'level', 'public', 'rm_na', 'simple_datetime', 'split_arrays', 'split_ppt', 'stations', 'type', 'tz', 'units', 'wide'],
  '/observations/': ['active', 'dates', 'day', 'elements', 'end_time', 'hour', 'latest', 'level', 'public', 'rm_na', 'simple_datetime', 'split_arrays', 'split_ppt', 'start_time', 'stations', 'type', 'tz', 'units', 'wide'],
  '/observations/charge/{station}/': ['end_time', 'start_time', 'type'],
  '/observations/daily/': ['active', 'agg_func', 'dates', 'elements', 'end_time', 'latest', 'level', 'na_info', 'public', 'rm_na', 'simple_datetime', 'split_arrays', 'split_ppt', 'start_time', 'stations', 'type', 'tz', 'units', 'wide'],
  '/observations/flags/': ['elements', 'end_time', 'start_time', 'stations', 'type', 'tz'],
  '/observations/grouped/': ['active', 'agg_func', 'dates', 'day', 'elements', 'end_time', 'hour', 'latest', 'level', 'nomid', 'public', 'rm_na', 'simple_datetime', 'split_ppt', 'start_time', 'stations', 'type', 'tz', 'units', 'wide'],
  '/observations/hourly/': ['active', 'agg_func', 'dates', 'elements', 'end_time', 'latest', 'level', 'na_info', 'public', 'rm_na', 'simple_datetime', 'split_arrays', 'split_ppt', 'start_time', 'stations', 'type', 'tz', 'units', 'wide'],
  '/photos/': ['type'],
  '/photos/{station}/': ['direction', 'dt', 'force', 'tz', 'web'],
  '/photos/{station}/{direction}/': ['dt', 'force', 'tz', 'web'],
  '/qaqc/': ['date', 'elements', 'n', 'raw', 'stations', 'type'],
  '/stations/': ['active', 'public', 'type'],
  '/stations/status/': ['type'],
}

/** Routes the API serves but omits from the spec. */
export const HIDDEN_PARAM_ALLOWLIST: Readonly<Record<string, readonly string[]>> = {
  // Lab retention points (station, Depth [cm], KPA, VWC) for SWP clipping.
  '/derived/swp/': ['stations', 'type'],
}

export const PARAM_ALLOWLIST: Readonly<Record<string, readonly string[]>> = {
  ...SPEC_PARAM_ALLOWLIST,
  ...HIDDEN_PARAM_ALLOWLIST,
}
