// Fidelity harness configuration: targets, API bases, station matrix, scenarios.
//
// Everything here is overridable by env var so the harness can be pointed at a
// preview deploy, a different legacy port, etc. URL builders live here (not in
// the drivers) so that when url-state keys change (Wave 1a: vars -> lv/sv,
// per-tab from/to) only this file needs editing.
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { readFileSync } from 'node:fs'

const __dirname = dirname(fileURLToPath(import.meta.url))

export const DEFAULT_OUT =
  process.env.FIDELITY_OUT ??
  '/private/tmp/claude-502/-Users-kyle-bocinsky-git-mt-climate-office-mesonet-dashboard/555463de-5eec-40b0-b395-8671a17ecca8/scratchpad/fidelity-out'

/** Cache dir for slow metadata (photos/ takes ~25-80 s). */
export const CACHE_DIR = process.env.FIDELITY_CACHE ?? join(DEFAULT_OUT, '_cache')

export const API = {
  v2: process.env.MESONET_V2 ?? 'https://mesonet2.climate.umt.edu/api/v2/',
  legacy: process.env.MESONET_LEGACY_API ?? 'https://mesonet.climate.umt.edu/api/',
}

/**
 * Targets. `kind` selects the driver (legacy Dash vs new React app).
 * stationUrl(station, opts) returns the deep link the driver loads first.
 */
export const TARGETS = {
  prodLegacy: {
    kind: 'legacy',
    label: 'Production legacy (mesonet.climate.umt.edu/dash, old API)',
    base: process.env.PROD_LEGACY_URL ?? 'https://mesonet.climate.umt.edu/dash',
  },
  localLegacy: {
    kind: 'legacy',
    label: 'Local legacy (audit/legacy-shim on mesonet2)',
    base: process.env.LOCAL_LEGACY_URL ?? 'http://127.0.0.1:8050',
  },
  newApp: {
    kind: 'new',
    label: 'New React app',
    base: process.env.NEW_URL ?? 'http://localhost:5173/mesonet-dashboard',
  },
}

export function legacyUrl(target, station, hash = '') {
  const b = target.base.replace(/\/$/, '')
  return `${b}/${station ? `${station}/` : ''}${hash}`
}

/**
 * New-app deep link. Keys mirror web/src/lib/url-state.ts as of origin/main
 * (s, agg, gridmet, card, info, vars; ag: var, crop, time, lt, soilv, annv;
 * downloader: els, period, pub, rmna, from, to). Update here after Wave 1a.
 */
export function newAppUrl(target, station, { tab = 'latest', params = {} } = {}) {
  const b = target.base.replace(/\/$/, '') + '/'
  const q = new URLSearchParams()
  if (station) q.set('s', station)
  for (const [k, v] of Object.entries(params)) {
    if (v === undefined || v === null) continue
    q.set(k, Array.isArray(v) ? v.join(',') : String(v))
  }
  const qs = q.toString()
  return `${b}${qs ? `?${qs}` : ''}${tab && tab !== 'latest' ? `#${tab}` : ''}`
}

/** Station matrix (generated by select-stations.mjs, committed for reproducibility). */
export function loadStations() {
  try {
    return JSON.parse(readFileSync(join(__dirname, 'stations.json'), 'utf8')).stations
  } catch {
    return [{ station: 'acebozem', roles: ['fallback'], why: 'stations.json missing; run select-stations.mjs' }]
  }
}

/**
 * Latest-Data scenarios. `legacy` = steps for the Dash driver; `newParams` =
 * URL params for the new app (it is URL-driven so no clicking needed for most).
 */
export const LATEST_SCENARIOS = [
  { id: 'default', label: 'Default (hourly, all default vars)', legacy: [], newParams: {} },
  {
    id: 'daily-gridmet',
    label: 'Daily + gridMET normals',
    legacy: [{ chip: ['hourly-switch', 'Daily'] }, { switch: 'gridmet-switch' }],
    newParams: { agg: 'daily', gridmet: true },
  },
  { id: 'daily', label: 'Daily (no normals)', legacy: [{ chip: ['hourly-switch', 'Daily'] }], newParams: { agg: 'daily' } },
  { id: 'raw', label: 'Raw', legacy: [{ chip: ['hourly-switch', 'Raw'] }], newParams: { agg: 'raw' } },
  // top cards
  { id: 'card-wind', label: 'Top card: Wind rose', legacy: [{ seg: ['ul-tabs', 'Wind Rose'] }], newParams: { card: 'wind' } },
  { id: 'card-forecast', label: 'Top card: Weather forecast', legacy: [{ seg: ['ul-tabs', 'Weather Forecast'] }], newParams: { card: 'forecast' } },
  { id: 'card-photo', label: 'Top card: Latest photo', legacy: [{ seg: ['ul-tabs', 'Latest Photo'] }], newParams: { card: 'photo' } },
  // bottom cards (legacy default is Current Conditions; new default is map)
  { id: 'info-map', label: 'Bottom card: Locator map', legacy: [{ seg: ['bl-tabs', 'Locator Map'] }], newParams: { info: 'map' } },
  { id: 'info-metadata', label: 'Bottom card: Station metadata', legacy: [{ seg: ['bl-tabs', 'Station Metadata'] }], newParams: { info: 'metadata' } },
  { id: 'info-current', label: 'Bottom card: Current conditions', legacy: [{ seg: ['bl-tabs', 'Current Conditions'] }], newParams: { info: 'current' } },
]

/** Default set used by `data-parity` (prod legacy vs local legacy). */
export const DATA_PARITY_SCENARIOS = ['default', 'daily', 'daily-gridmet']

/** Downloader scenarios: period x element set; dates fixed relative to today. */
export const DOWNLOADER_SCENARIOS = [
  { id: 'dl-daily', period: 'daily', elements: ['air_temp_0200', 'ppt', 'rh'], days: 30 },
  { id: 'dl-hourly', period: 'hourly', elements: ['air_temp_0200', 'wind_spd', 'sol_rad'], days: 7 },
  { id: 'dl-monthly', period: 'monthly', elements: ['air_temp_0200', 'ppt'], days: 365 },
]

/**
 * Ag comparisons (new app vs /derived without premade, keep=true).
 * `derived` = /derived endpoint params; `newParams` = new-app URL params.
 */
export const AG_SCENARIOS = [
  { id: 'etr', derived: { period: 'daily', elements: 'etr' }, newParams: { var: 'etr' } },
  { id: 'gdd-wheat', derived: { period: 'daily', elements: 'gdd', crop: 'wheat' }, newParams: { var: 'gdd', crop: 'wheat' } },
  { id: 'gdd-corn', derived: { period: 'daily', elements: 'gdd', crop: 'corn' }, newParams: { var: 'gdd', crop: 'corn' } },
  { id: 'feels-like', derived: { period: 'hourly', elements: 'feels_like' }, newParams: { var: 'feels_like', time: 'hourly' } },
  { id: 'cci', derived: { period: 'hourly', elements: 'cci' }, newParams: { var: 'cci', time: 'hourly' } },
  { id: 'swp', derived: { period: 'daily', elements: 'swp' }, newParams: { var: 'swp' }, needsSwp: true },
  {
    id: 'percent-saturation',
    derived: { period: 'daily', elements: 'percent_saturation' },
    newParams: { var: 'percent_saturation' },
    needsSwp: true,
  },
]

/** Numeric tolerances for the comparator. */
export const TOLERANCE = {
  abs: Number(process.env.FIDELITY_ABS_TOL ?? 0.0011),
  rel: Number(process.env.FIDELITY_REL_TOL ?? 2e-4),
  /** fraction of points allowed to differ before a trace is a FAIL (vs WARN) */
  maxDiffFrac: 0.0,
}

/** Timeouts (ms). Dash on prod can be slow; photos/ is ~25-80 s. */
export const TIMEOUTS = {
  nav: 120_000,
  plot: 150_000,
  settleQuiet: 2_500,
}
