#!/bin/bash

sudo su - -c "R -q -e \"install.packages('rgdal', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('dplyr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('leaflet', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('leaflet.extras', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('knitr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('RCurl', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('tidyverse', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('rmarkdown', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('flexdashboard', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('htmlwidgets', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('plotly', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('data.table', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('doParallel', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('htmltools', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('knitr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('kableExtra', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('units', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('lubridate', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('stringr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('plyr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('jquerylib', repos='http://cran.rstudio.com/')\""

